### ISSUE TITLE
Can flatpaks know the default timezone?

### ISSUE THREAD

**Issue by detrout** [flathub/org.kde.kontact#9]
When creating an appointment in the calendar, I select a time, enter information and then the appointment jumps several hours earlier. 

I discovered the default timzeone appears to be "Universal", and that after I save the appointment, the appointment's timezone changes to UTC. Considering I'm in the America/Los_Angeles timezone, that's ends up being a a pretty big jump.

It looks like /etc/timezone is set to "Universal" in the container.

```
flatpak run --command=/bin/bash  org.kde.kontact/x86_64/stable
bash-4.3$ cat /etc/timezone
Universal
```

**Comment by TingPing** [comment]
`/etc/localtime` contains your timezone.

**Comment by danvratil** [comment]
This issue has been fixed in Flatpak itself, so we can close this.

**Comment by autoteelar** [comment]
its still happening to me, using UTC instead of my current set timezone

**Comment by travier** [comment]
I can't reproduce that:
```
$ ls -l /etc/localtime
lrwxrwxrwx. 1 root root 34 Feb 11  2018 /etc/localtime -> ../usr/share/zoneinfo/Europe/Paris
$ flatpak run --command=bash org.kde.ark
$ cat /etc/timezone 
Europe/Paris
$ ls -alh /etc/localtime 
lrwxrwxrwx. 1 tim tim 34 Oct 27 12:45 /etc/localtime -> ../usr/share/zoneinfo/Europe/Paris
```

**Comment by autoteelar** [comment]
its not exactly that, i didnt run any commands. i just installed element desktop and realized all the time zones are UTC but if i use element-desktop from my package manager or tarball it shows my local time 

and yeah, ls -l /etc/localtime shows my proper time zone too

oh but when i do this 

$ flatpak run --command=bash im.riot.Riot
$ cat /etc/timezone 
UTC
$ 

it shows utc

so i could probably edit that specific file saying UTC right?

$ ls -alh /etc/localtime
lrwxrwxrwx 1 ichigo ichigo 25 10月 27 12:25 /etc/localtime -> ../usr/share/zoneinfo/UTC

**Comment by travier** [comment]
You're on the issue tracker for org.kde.kontact. Please file an issue in the right place.

**Comment by travier** [comment]
Can't reproduce that either:
```
$ flatpak run --command=bash im.riot.Riot
[📦 im.riot.Riot ~]$ cat /etc/timezone 
Europe/Paris
[📦 im.riot.Riot ~]$ ls -alh /etc/localtime 
lrwxrwxrwx. 1 tim tim 34 Oct 27 15:33 /etc/localtime -> ../usr/share/zoneinfo/Europe/Paris
```

**Comment by autoteelar** [comment]
i thought this was for the flatpak repo, my bad this result just pinged on the search engine, is this a flatpak universal issue or per program? i dont know how flatpak works really

**Comment by autoteelar** [comment]
thank you for confirming that it doesnt happen to you on riot, something must be up with my distro. i will have to close this then as its probably my distro
